// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfn-WODDYxXUF_GtB6JupEltGKDlSkrU',
    appId: '1:817523830758:web:4059660fe5db9aa2e9f027',
    messagingSenderId: '817523830758',
    projectId: 'lista-casamento-fb6aa',
    authDomain: 'lista-casamento-fb6aa.firebaseapp.com',
    storageBucket: 'lista-casamento-fb6aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1bXPd4JJBYm8pAoBu3G902K4fJogzZHI',
    appId: '1:817523830758:android:29c0077ca5d5ccebe9f027',
    messagingSenderId: '817523830758',
    projectId: 'lista-casamento-fb6aa',
    storageBucket: 'lista-casamento-fb6aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvhsXuc_P3rntznou9YYwWMsvPgBMSDEw',
    appId: '1:817523830758:ios:83266cf10998cb0ce9f027',
    messagingSenderId: '817523830758',
    projectId: 'lista-casamento-fb6aa',
    storageBucket: 'lista-casamento-fb6aa.firebasestorage.app',
    iosBundleId: 'com.example.listaDePresentes',
  );
}
